# cperl 5, version 27
# perl 5, version 22
# shondal 9.16.2018
`perl -e '$x = "Help Im Falling off the screeeeeen... no seriously... ok fine... bye..."; while  ( $x =~ m{(?=(.*))}g ) { print "$1 $2\n" }'`
~~~~
Help Im Falling off the screeeeeen... no seriously... ok fine... bye... 
elp Im Falling off the screeeeeen... no seriously... ok fine... bye... 
lp Im Falling off the screeeeeen... no seriously... ok fine... bye... 
p Im Falling off the screeeeeen... no seriously... ok fine... bye... 
 Im Falling off the screeeeeen... no seriously... ok fine... bye... 
Im Falling off the screeeeeen... no seriously... ok fine... bye... 
m Falling off the screeeeeen... no seriously... ok fine... bye... 
 Falling off the screeeeeen... no seriously... ok fine... bye... 
Falling off the screeeeeen... no seriously... ok fine... bye... 
alling off the screeeeeen... no seriously... ok fine... bye... 
lling off the screeeeeen... no seriously... ok fine... bye... 
ling off the screeeeeen... no seriously... ok fine... bye... 
ing off the screeeeeen... no seriously... ok fine... bye... 
ng off the screeeeeen... no seriously... ok fine... bye... 
g off the screeeeeen... no seriously... ok fine... bye... 
 off the screeeeeen... no seriously... ok fine... bye... 
off the screeeeeen... no seriously... ok fine... bye... 
ff the screeeeeen... no seriously... ok fine... bye... 
f the screeeeeen... no seriously... ok fine... bye... 
 the screeeeeen... no seriously... ok fine... bye... 
the screeeeeen... no seriously... ok fine... bye... 
he screeeeeen... no seriously... ok fine... bye... 
e screeeeeen... no seriously... ok fine... bye... 
 screeeeeen... no seriously... ok fine... bye... 
screeeeeen... no seriously... ok fine... bye... 
creeeeeen... no seriously... ok fine... bye... 
reeeeeen... no seriously... ok fine... bye... 
eeeeeen... no seriously... ok fine... bye... 
eeeeen... no seriously... ok fine... bye... 
eeeen... no seriously... ok fine... bye... 
eeen... no seriously... ok fine... bye... 
een... no seriously... ok fine... bye... 
en... no seriously... ok fine... bye... 
n... no seriously... ok fine... bye... 
... no seriously... ok fine... bye... 
.. no seriously... ok fine... bye... 
. no seriously... ok fine... bye... 
 no seriously... ok fine... bye... 
no seriously... ok fine... bye... 
o seriously... ok fine... bye... 
 seriously... ok fine... bye... 
seriously... ok fine... bye... 
eriously... ok fine... bye... 
riously... ok fine... bye... 
iously... ok fine... bye... 
ously... ok fine... bye... 
usly... ok fine... bye... 
sly... ok fine... bye... 
ly... ok fine... bye... 
y... ok fine... bye... 
... ok fine... bye... 
.. ok fine... bye... 
. ok fine... bye... 
 ok fine... bye... 
ok fine... bye... 
k fine... bye... 
 fine... bye... 
fine... bye... 
ine... bye... 
ne... bye... 
e... bye... 
... bye... 
.. bye... 
. bye... 
 bye... 
bye... 
ye... 
e... 
... 
.. 
. 
~~~~
